CREATE TABLE "guests" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "first_name" varchar(50),
                          "last_name" varchar(50),
                          "date_of_birth" date,
                          "phone" varchar(30),
                          "email" varchar(100) UNIQUE NOT NULL,
                          "passport_number" varchar(50),
                          "nationality" varchar(50),
                          "gender" varchar(10),
                          "address" text,
                          "loyalty_points" int DEFAULT 0,
                          "created_at" timestamp DEFAULT (now()),
                          "updated_at" timestamp DEFAULT (now())
);
