CREATE TABLE "bookings" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "booking_reference" varchar(50) UNIQUE NOT NULL,
                            "guest_id" bigint NOT NULL,
                            "guest_name" varchar(100),
                            "guest_email" varchar(100),
                            "room_id" bigint NOT NULL,
                            "room_number" varchar(10),
                            "room_type_name" varchar(30),
                            "check_in_date" date NOT NULL,
                            "check_out_date" date NOT NULL,
                            "actual_check_in" timestamp,
                            "actual_check_out" timestamp,
                            "num_guests" int,
                            "booking_type" varchar(30),
                            "total_amount" decimal(10,2),
                            "discount_amount" decimal(10,2) DEFAULT 0,
                            "tax_amount" decimal(10,2) DEFAULT 0,
                            "final_amount" decimal(10,2),
                            "status" varchar(30) DEFAULT 'Pending',
                            "special_requests" text,
                            "cancellation_reason" text,
                            "created_by" bigint,
                            "promotion_id" bigint,
                            "created_at" timestamp DEFAULT (now()),
                            "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "promotions" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "code" varchar(50) UNIQUE,
                              "description" text,
                              "discount_percentage" decimal(5,2),
                              "start_date" date,
                              "end_date" date,
                              "active" boolean DEFAULT true
);

CREATE TABLE "reviews" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "booking_id" bigint NOT NULL,
                           "guest_id" bigint NOT NULL,
                           "guest_name" varchar(100),
                           "rating" int NOT NULL,
                           "comment" text,
                           "created_at" timestamp DEFAULT (now())
);
