CREATE TABLE "staff" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "first_name" varchar(50),
                         "last_name" varchar(50),
                         "date_of_birth" date,
                         "citizenship" varchar(50),
                         "email" varchar(100) UNIQUE NOT NULL,
                         "phone" varchar(30),
                         "username" varchar(50) UNIQUE NOT NULL,
                         "password_hash" varchar(255) NOT NULL,
                         "role" varchar(30),
                         "department" varchar(50),
                         "salary" decimal(10,2),
                         "hire_date" date,
                         "status" varchar(20) DEFAULT 'Active',
                         "created_at" timestamp DEFAULT (now()),
                         "updated_at" timestamp DEFAULT (now())
);

