CREATE TABLE "services" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100) UNIQUE NOT NULL,
                            "description" text,
                            "price" decimal(10,2) NOT NULL,
                            "category" varchar(50),
                            "status" varchar(20) DEFAULT 'Available',
                            "created_at" timestamp DEFAULT (now()),
                            "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "booking_services" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "booking_id" bigint NOT NULL,
                                    "booking_reference" varchar(50),
                                    "service_id" bigint NOT NULL,
                                    "service_name" varchar(100),
                                    "staff_id" bigint,
                                    "staff_name" varchar(100),
                                    "quantity" int DEFAULT 1,
                                    "unit_price" decimal(10,2) NOT NULL,
                                    "total_price" decimal(10,2),
                                    "service_date" date DEFAULT (current_date),
                                    "notes" text,
                                    "created_at" timestamp DEFAULT (now())
);
