spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Correlation-ID, "#{T(java.util.UUID).randomUUID()}"
        - AddResponseHeader=X-Gateway-log, Active

      routes:
        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/v1/guest/**
          filters:
            - StripPrefix=3
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: loyalty-service
          uri: lb://LOYALTY-SERVICE
          predicates:
            - Path=/api/v1/loyalty/**
          filters:
            - StripPrefix=3
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/bookings/**
            - Path=/api/v1/promotions/**
            - Path=/api/v1/reviews/**
            - Path=/api/v1/guests/**
            - Path=/api/v1/loyalty/**
            - Path=/api/v1/rooms/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=X-Request-Id, "#{T(java.util.UUID).randomUUID()}"
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: bookingCircuit
                fallbackUri: forward:/fallback/booking

        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/room/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: staff-service
          uri: lb://STAFF-SERVICE
          predicates:
            - Path=/api/v1/staffs/**
          filters:
            - StripPrefix=3
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: service-management
          uri: lb://SERVICE-MANAGEMENT
          predicates:
            - Path=/api/v1/service/**
          filters:
            - StripPrefix=3
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
