-- =========================
-- TABLE: room_types
-- =========================
CREATE TABLE room_types (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(30) UNIQUE NOT NULL,
                            description TEXT,
                            price_per_night DECIMAL(10,2) NOT NULL,
                            max_occupancy INT NOT NULL,
                            bed_type VARCHAR(30),
                            amenities JSON,
                            base_image_url VARCHAR(255),
                            created_at TIMESTAMP DEFAULT now(),
                            updated_at TIMESTAMP DEFAULT now()
);

COMMENT ON TABLE room_types IS 'Master table defining room categories';

COMMENT ON COLUMN room_types.id IS 'Primary key';
COMMENT ON COLUMN room_types.name IS 'Room type name (Standard, Deluxe, Suite)';
COMMENT ON COLUMN room_types.description IS 'Detailed room type description';
COMMENT ON COLUMN room_types.price_per_night IS 'Price per night';
COMMENT ON COLUMN room_types.max_occupancy IS 'Maximum allowed guests';
COMMENT ON COLUMN room_types.bed_type IS 'Type of bed (Single, Double, King)';
COMMENT ON COLUMN room_types.amenities IS 'Amenities list in JSON format';
COMMENT ON COLUMN room_types.base_image_url IS 'Main image URL';
COMMENT ON COLUMN room_types.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN room_types.updated_at IS 'Last update timestamp';

-- =========================
-- TABLE: rooms
-- =========================
CREATE TABLE rooms (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       room_number VARCHAR(10) UNIQUE NOT NULL,
                       room_type_id BIGINT NOT NULL,
                       floor INT,
                       status VARCHAR(30) DEFAULT 'Available',
                       breakfast_included BOOLEAN DEFAULT false,
                       is_smoking BOOLEAN DEFAULT false,
                       features JSON,
                       created_at TIMESTAMP DEFAULT now(),
                       updated_at TIMESTAMP DEFAULT now(),

                       CONSTRAINT fk_rooms_room_type
                           FOREIGN KEY (room_type_id)
                               REFERENCES room_types(id)
);

COMMENT ON TABLE rooms IS 'Physical hotel rooms';

COMMENT ON COLUMN rooms.id IS 'Primary key';
COMMENT ON COLUMN rooms.room_number IS 'Unique room number';
COMMENT ON COLUMN rooms.room_type_id IS 'Foreign key to room_types';
COMMENT ON COLUMN rooms.floor IS 'Floor number';
COMMENT ON COLUMN rooms.status IS 'Room availability status';
COMMENT ON COLUMN rooms.breakfast_included IS 'Is breakfast included';
COMMENT ON COLUMN rooms.is_smoking IS 'Smoking allowed or not';
COMMENT ON COLUMN rooms.features IS 'Extra features in JSON';
COMMENT ON COLUMN rooms.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN rooms.updated_at IS 'Last update timestamp';

-- =========================
-- TABLE: room_images
-- =========================
CREATE TABLE room_images (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             room_id BIGINT NOT NULL,
                             image_url VARCHAR(255),
                             description TEXT,
                             created_at TIMESTAMP DEFAULT now(),

                             CONSTRAINT fk_room_images_room
                                 FOREIGN KEY (room_id)
                                     REFERENCES rooms(id)
);

COMMENT ON TABLE room_images IS 'Images related to rooms';

COMMENT ON COLUMN room_images.id IS 'Primary key';
COMMENT ON COLUMN room_images.room_id IS 'Foreign key to rooms';
COMMENT ON COLUMN room_images.image_url IS 'Image URL';
COMMENT ON COLUMN room_images.description IS 'Image description';
COMMENT ON COLUMN room_images.created_at IS 'Image upload timestamp';

-- =========================
-- TABLE: maintenance
-- =========================
CREATE TABLE maintenance (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             room_id BIGINT NOT NULL,
                             staff_id BIGINT,
                             issue_type VARCHAR(100),
                             description TEXT,
                             priority VARCHAR(20) DEFAULT 'Low',
                             status VARCHAR(30) DEFAULT 'Reported',
                             reported_date TIMESTAMP DEFAULT now(),
                             completed_date TIMESTAMP,
                             estimated_cost DECIMAL(10,2),
                             room_condition_before TEXT,
                             room_condition_after TEXT,

                             CONSTRAINT fk_maintenance_room
                                 FOREIGN KEY (room_id)
                                     REFERENCES rooms(id)
);

COMMENT ON TABLE maintenance IS 'Maintenance and repair records for rooms';

COMMENT ON COLUMN maintenance.id IS 'Primary key';
COMMENT ON COLUMN maintenance.room_id IS 'Foreign key to rooms';
COMMENT ON COLUMN maintenance.staff_id IS 'Staff responsible for maintenance';
COMMENT ON COLUMN maintenance.issue_type IS 'Type of maintenance issue';
COMMENT ON COLUMN maintenance.description IS 'Issue description';
COMMENT ON COLUMN maintenance.priority IS 'Maintenance priority';
COMMENT ON COLUMN maintenance.status IS 'Maintenance status';
COMMENT ON COLUMN maintenance.reported_date IS 'Issue reported timestamp';
COMMENT ON COLUMN maintenance.completed_date IS 'Maintenance completion timestamp';
COMMENT ON COLUMN maintenance.estimated_cost IS 'Estimated repair cost';
COMMENT ON COLUMN maintenance.room_condition_before IS 'Room condition before repair';
COMMENT ON COLUMN maintenance.room_condition_after IS 'Room condition after repair';
