-- =========================
-- TABLE: room_types
-- =========================
CREATE TABLE IF NOT EXISTS room_types (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(30) UNIQUE NOT NULL,
    description TEXT,
    price_per_night DECIMAL(10,2) NOT NULL,
    max_occupancy INT NOT NULL,
    bed_type VARCHAR(30),
    amenities JSON,
    base_image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
    );

-- =========================
-- TABLE: rooms
-- =========================
CREATE TABLE IF NOT EXISTS rooms (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     room_number VARCHAR(10) UNIQUE NOT NULL,
    room_type_id BIGINT NOT NULL,
    floor INT,
    status VARCHAR(30) DEFAULT 'Available',
    breakfast_included BOOLEAN DEFAULT false,
    is_smoking BOOLEAN DEFAULT false,
    features JSON,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now(),

    CONSTRAINT fk_rooms_room_type
    FOREIGN KEY (room_type_id)
    REFERENCES room_types(id)
    );

-- =========================
-- TABLE: room_images
-- =========================
CREATE TABLE IF NOT EXISTS room_images (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           room_id BIGINT NOT NULL,
                                           image_url VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT now(),

    CONSTRAINT fk_room_images_room
    FOREIGN KEY (room_id)
    REFERENCES rooms(id)
    );

-- =========================
-- TABLE: maintenance
-- =========================
CREATE TABLE IF NOT EXISTS maintenance (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           room_id BIGINT NOT NULL,
                                           staff_id BIGINT,
                                           issue_type VARCHAR(100),
    description TEXT,
    priority VARCHAR(20) DEFAULT 'Low',
    status VARCHAR(30) DEFAULT 'Reported',
    reported_date TIMESTAMP DEFAULT now(),
    completed_date TIMESTAMP,
    estimated_cost DECIMAL(10,2),
    room_condition_before TEXT,
    room_condition_after TEXT,

    CONSTRAINT fk_maintenance_room
    FOREIGN KEY (room_id)
    REFERENCES rooms(id)
    );