CREATE TABLE "loyalty_transactions" (
                                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        "guest_id" bigint NOT NULL,
                                        "points" int,
                                        "type" varchar(20),
                                        "description" text,
                                        "transaction_date" timestamp DEFAULT (now())
);
